# Generated by Django 5.0.3 on 2024-10-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_room_adults_room_children_room_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='children',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='adults',
        ),
    ]
