# Generated by Django 5.0.3 on 2024-10-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='x', max_length=15),
        ),
    ]
